#!/usr/bin/env node
// Emits the colour layer of every config from tools/tokens.mjs.
//
//   node tools/build.mjs           write generated files
//   node tools/build.mjs --check   fail if any generated file is out of date
//
// Palette drift across apps is the exact bug this repo used to have (four
// different neutral families under one accent). Generating instead of
// hand-editing makes that failure mode structurally impossible.

import { writeFileSync, readFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  ink, accent, state, surfaceTint, semantic, ansi, categorical, bgChrome, stateOnChrome, meta,
} from './tokens.mjs';
import { argb, bare, hex } from './color.mjs';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const BANNER = 'GENERATED by tools/build.mjs from tools/tokens.mjs — do not edit by hand.';

const out = [];
function emit(relPath, content) {
  out.push({ relPath, content });
}

// ── pi theme ────────────────────────────────────────────────────────────────
// The schema is additionalProperties:false with 52 valid keys, so every key
// below is required to exist and no others may appear.
//
// NOTE: values are literal hex, with no `vars` indirection. pi resolves `vars`
// at load time and a single typo in a var name silently falls back to the
// stock dark theme with no error — the previous theme was one character away
// from that failure because its var names shadowed token names
// (`"borderMuted": "borderMuted"`). Generated output has no reason to indirect.
const piTheme = {
  $schema:
    'https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json',
  name: meta.slug,
  colors: {
    accent: accent.base,
    // Neutral, NOT accent: pi runs inside a cmux pane that already draws an
    // accent-coloured focus border. Two nested accent outlines is the
    // "stacked focus rings" problem — see docs/DESIGN.md.
    border: ink[5],
    borderAccent: accent.base,
    borderMuted: ink[4],

    success: state.success,
    error: state.error,
    warning: state.warning,
    muted: ink[7],
    dim: ink[6],
    text: ink[8],
    thinkingText: ink[6],

    selectedBg: accent.wash,
    userMessageBg: ink[2],
    userMessageText: ink[8],
    customMessageBg: surfaceTint.special,
    customMessageText: ink[8],
    customMessageLabel: state.special,
    toolPendingBg: surfaceTint.pending,
    toolSuccessBg: surfaceTint.success,
    toolErrorBg: surfaceTint.error,
    // Bright neutral rather than accent: tool titles appear on nearly every
    // line of a session. Accent-colouring them would drown the accent.
    toolTitle: ink[9],
    toolOutput: ink[7],

    mdHeading: accent.bright,
    mdLink: state.info,
    mdLinkUrl: ink[6],
    mdCode: state.warning,
    mdCodeBlock: ink[8],
    mdCodeBlockBorder: ink[4],
    mdQuote: ink[7],
    mdQuoteBorder: accent.deep,
    mdHr: ink[4],
    mdListBullet: accent.base,

    toolDiffAdded: state.success,
    toolDiffRemoved: state.error,
    toolDiffContext: ink[6],

    // Syntax hierarchy by frequency: the things you skim past are dimmest,
    // the things that carry structure are brightest.
    syntaxComment: ink[6],
    syntaxKeyword: state.special,
    syntaxFunction: accent.base,
    syntaxVariable: ink[8],
    syntaxString: state.success,
    syntaxNumber: state.warning,
    syntaxType: state.info,
    syntaxOperator: accent.dim,
    syntaxPunctuation: ink[7],

    // An intensity ramp, entirely within the accent hue: reasoning effort
    // climbs from cold neutral to a lit violet-white.
    //
    // It used to jump to amber at xhigh and yellow at max. Two problems. A hue
    // change reads as a change of KIND rather than of degree, so "more effort"
    // looked like "different mode". And with xhigh as the default it was not a
    // ramp at all — just a permanently amber dot, the only warm pixel in a
    // violet interface.
    thinkingOff: ink[5],
    thinkingMinimal: accent.deep,
    thinkingLow: accent.dim,
    thinkingMedium: accent.base,
    thinkingHigh: accent.bright,
    thinkingXhigh: accent.pale,
    thinkingMax: accent.lit,

    bashMode: state.info,
  },
  // Only these three keys are permitted, and they affect /export HTML only.
  export: { pageBg: ink[0], cardBg: ink[1], infoBg: ink[2] },
};
emit(`pi/themes/${meta.slug}.json`, JSON.stringify(piTheme, null, 2) + '\n');

// ── ghostty theme ───────────────────────────────────────────────────────────
// Shipped as a theme FILE rather than inline keys, so `theme = iris` in the
// main config stays readable and the palette can be swapped atomically.
const ghosttyTheme = `# ${BANNER}
# ${meta.name} — ${meta.appearance}

palette = 0=#${bare(ansi.black)}
palette = 1=#${bare(ansi.red)}
palette = 2=#${bare(ansi.green)}
palette = 3=#${bare(ansi.yellow)}
palette = 4=#${bare(ansi.blue)}
palette = 5=#${bare(ansi.magenta)}
palette = 6=#${bare(ansi.cyan)}
palette = 7=#${bare(ansi.white)}
palette = 8=#${bare(ansi.brightBlack)}
palette = 9=#${bare(ansi.brightRed)}
palette = 10=#${bare(ansi.brightGreen)}
palette = 11=#${bare(ansi.brightYellow)}
palette = 12=#${bare(ansi.brightBlue)}
palette = 13=#${bare(ansi.brightMagenta)}
palette = 14=#${bare(ansi.brightCyan)}
palette = 15=#${bare(ansi.brightWhite)}

background = #${bare(semantic.bgBase)}
foreground = #${bare(semantic.text)}

cursor-color = #${bare(accent.base)}
cursor-text = #${bare(ink[0])}

selection-background = #${bare(accent.wash)}
selection-foreground = #${bare(ink[9])}
`;
emit('ghostty/themes/' + meta.slug, ghosttyTheme);

// ── sketchybar colours ──────────────────────────────────────────────────────
// Variable NAMES are load-bearing: sketchybarrc and every plugin script
// reference them. Renaming a variable silently yields a transparent item, so
// the existing names are preserved and only their values change.
const sb = `#!/usr/bin/env bash
# ${BANNER}
# ${meta.name} palette for sketchybar. 0xAARRGGBB.

# ── Ramp ───────────────────────────────────────────────────────────────────
export INK0=${argb(ink[0])}
export INK1=${argb(ink[1])}
export INK2=${argb(ink[2])}
export INK3=${argb(ink[3])}
export INK4=${argb(ink[4])}
export INK5=${argb(ink[5])}
export INK6=${argb(ink[6])}
export INK7=${argb(ink[7])}
export INK8=${argb(ink[8])}
export INK9=${argb(ink[9])}

# ── Named slots (referenced by sketchybarrc and plugins/) ──────────────────
export BLACK=${argb(ink[0])}
export WHITE=${argb(ink[8])}
export GREY=${argb(ink[6])}
# Lifted variants: these are drawn ON the bar, which is much lighter than a
# terminal, and the normal set drops under 3:1 there.
export RED=${argb(stateOnChrome.error)}
export GREEN=${argb(stateOnChrome.success)}
export YELLOW=${argb(stateOnChrome.warning)}
export ORANGE=${argb(stateOnChrome.warning)}
export BLUE=${argb(stateOnChrome.special)}
export CYAN=${argb(stateOnChrome.info)}
export MAGENTA=${argb(accent.base)}
export TRANSPARENT=0x00000000

# ── Semantic ───────────────────────────────────────────────────────────────
export ACCENT=${argb(accent.base)}
export ACCENT_TRANSPARENT=${argb(accent.base, 0.27)}
export GREY_TRANSP=${argb(ink[6], 0.27)}

# The bar itself is translucent so the wallpaper reads through; items sit on
# opaque-enough fills to keep their labels legible over any wallpaper region.
export BAR_COLOR=${argb(bgChrome, 0.42)}
export BG0=${argb(bgChrome, 0.8)}
export BG1=${argb(bgChrome, 0.55)}
export BG2=${argb(bgChrome, 0.72)}

export ITEM_BG=${argb(bgChrome, 0.38)}
export ITEM_BG_ACTIVE=${argb(accent.wash, 0.67)}

# ── Fonts ──────────────────────────────────────────────────────────────────
# Exported here because every plugin already sources this file. Plugins used
# to hardcode "SF Pro", which is NOT installed on this machine — sketchybar
# silently falls back on an unknown family rather than erroring, so the icons
# rendered as tofu boxes while the config looked correct.
# Every glyph in icons.sh is verified against FONT_ICON's cmap table.
export FONT_UI="Helvetica Neue"
export FONT_ICON="JetBrainsMono Nerd Font"
`;
emit('sketchybar/colors.sh', sb);

// ── borders ─────────────────────────────────────────────────────────────────
// Width is deliberately thinner than the old 8.0: the window border is the
// OUTERMOST ring in a three-level focus hierarchy (window → cmux pane → nvim
// split). The outermost ring only needs to be found, not shouted.
const borders = `#!/bin/bash
# ${BANNER}
# ${meta.name} — window focus ring (outermost level of the focus hierarchy).

options=(
  style=round
  width=4.0
  hidpi=on
  active_color=${argb(accent.base)}
  inactive_color=${argb(ink[4], 0.53)}
)

borders "\${options[@]}"
`;
emit('borders/bordersrc', borders);

// ── swift tokens (CmuxDock) ─────────────────────────────────────────────────
// Emitted rather than hand-written for the same reason as everything else: a
// hand-copied hex in a second language is exactly how the four-palette drift
// started. AppKit wants linear 0-1 sRGB components, so the conversion happens
// here instead of at runtime.
const swiftColor = (name, h, note) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(h.slice(i, i + 2), 16) / 255);
  const f = (n) => n.toFixed(4);
  return `    static let ${name.padEnd(10)} = NSColor(srgbRed: ${f(r)}, green: ${f(g)}, blue: ${f(b)}, alpha: 1) // ${h}${note ? '  ' + note : ''}`;
};
const swiftTokens = `// ${BANNER}
// ${meta.name} tokens for the CmuxDock tile.

import AppKit

enum Iris {
${swiftColor('bgBase', ink[0])}
${swiftColor('bgRaised', ink[1])}
${swiftColor('bgPanel', ink[2])}
${swiftColor('bgChrome', bgChrome, '— system bar / notch island')}
${swiftColor('border', ink[4])}
${swiftColor('textDim', ink[6])}
${swiftColor('text', ink[8])}
${swiftColor('textBright', ink[9])}

    // Identity. Used for the resting ring only — never to signal a state.
${swiftColor('accent', accent.base)}

    // States. Ranked worst-wins by the tile.
${swiftColor('info', state.info, '— working')}
${swiftColor('warning', state.warning, '— needs attention')}
${swiftColor('error', state.error, '— failed')}

    // Lifted for the notch island, which sits on bgChrome.
${swiftColor('infoUp', stateOnChrome.info)}
${swiftColor('warningUp', stateOnChrome.warning)}
${swiftColor('errorUp', stateOnChrome.error)}
${swiftColor('accentUp', accent.bright)}
}
`;
emit('swift/CmuxDock/Sources/IrisTokens.swift', swiftTokens);

// ── cmux ────────────────────────────────────────────────────────────────────
// Generated whole rather than colour-only: it is pure declarative config, and
// generating it is what guarantees the palette cannot drift from the rest.
// Every key below was checked against the published schema; unknown keys are
// rejected by `tools/check-configs.sh`.
//
// NOTE: cmux takes its TERMINAL palette from ~/.config/ghostty/config, not
// from this file (`cmux themes list` confirms it resolves theme `iris` from
// there). So this file only styles cmux's own chrome.
const cmux = {
  $schema: 'https://raw.githubusercontent.com/manaflow-ai/cmux/main/web/data/cmux.schema.json',
  schemaVersion: 1,

  // Focus hierarchy, level 2 of 3. Each level uses a DIFFERENT mechanism so
  // they can never read as competing rings:
  //   1. window  — JankyBorders, thick 4px accent ring outside the window
  //   2. pane    — this, a thin accent line inside the window
  //   3. split   — Ghostty dims unfocused content, drawing no border at all
  paneBorderColor: ink[4],
  activePaneBorderColor: accent.base,

  app: {
    appearance: 'dark',
    appIcon: 'dark',
    minimalMode: false,
    newWorkspacePlacement: 'afterCurrent',
    workspaceInheritWorkingDirectory: true,
    confirmQuit: 'dirty-only',
    reorderOnNotification: true,
    // Keyboard navigation: make the palette and focus-cycling reach
    // everything, so the mouse is never required to get somewhere.
    commandPaletteSearchesAllSurfaces: true,
    focusHistoryIncludesPanesAndTabs: true,
    focusPaneOnFirstClick: true,
    openMarkdownInCmuxViewer: true,
  },

  terminal: {
    sessionContentAlignment: 'center',
    sessionContentMaxWidth: false,
    showScrollBar: true,
    scrollSpeed: 1,
    autoResumeAgentSessions: true,
    // Matches Ghostty's copy-on-select so selection behaves identically
    // whichever terminal surface you happen to be in.
    copyOnSelect: true,
  },

  notifications: {
    unreadPaneRing: true,
    // paneFlash is OFF deliberately. The unread ring already owns "this pane
    // has news", and a flashing pane edge competes with the focus border for
    // the same visual channel — a coloured edge. Two unrelated meanings, one
    // treatment, which is the confusion this system exists to prevent.
    paneFlash: false,
    dockBadge: true,
    showInMenuBar: true,
    sound: 'default',
    // Feeds the CmuxDock tile. This is `command`, not `hooks`, on purpose:
    // hooks receive notification-policy JSON on stdin and must return updated
    // policy on stdout within timeoutSeconds, and a failing hook makes cmux
    // fall back to default notification behaviour. A tile that draws an icon
    // has no business sitting in the delivery path — `command` is documented
    // as running *alongside* delivery, so a broken script cannot suppress a
    // notification.
    //
    // $HOME rather than an absolute path: this is run through a shell, so it
    // expands, and the repo does not get pinned to one machine's username.
    command: '"$HOME/.config/cmux/dock-hook.sh" >/dev/null 2>&1 &',
    // Never interrupt about the pane already being looked at.
    suppressOnlyFocusedSurface: true,
    // Sound and banner only when actually away from the machine.
    agentTurnComplete: 'whenIdle',
    agentIdleReminder: true,
    agentPermissionPrompt: true,
  },

  sidebar: {
    hideAllDetails: false,
    showBranchDirectory: true,
    showWorkspaceDescription: true,
    showNotificationMessage: true,
    showAgentActivity: true,
    showProgress: true,
    showPullRequests: true,
    makePullRequestsClickable: true,
    showPorts: true,
    showSSH: true,
    showLog: true,
    openPortLinksInCmuxBrowser: true,
    openPullRequestLinksInCmuxBrowser: true,
    watchGitStatus: true,
    wrapWorkspaceTitles: false,
    branchLayout: 'vertical',
    // 8 lines of notification text per row pushed real workspaces off screen
    // on a laptop display. 5 keeps the gist without costing a workspace slot.
    notificationMessageLineLimit: 5,
    // Split the two indicators to opposite ends: a spinner (transient, "busy")
    // and a badge (persistent, "unread") mean different things and must not
    // trade places in the same spot.
    loadingSpinnerPosition: 'leading',
    notificationBadgePosition: 'trailing',
  },

  workspaceColors: {
    indicatorStyle: 'washRail',
    selectionColor: accent.wash,
    // Amber, NOT the accent. The previous config used the accent colour here,
    // which made "this workspace is selected" and "this workspace needs you"
    // the same colour. Attention is a STATUS; the accent is IDENTITY.
    notificationBadgeColor: state.warning,
    colors: categorical,
  },

  sidebarAppearance: {
    matchTerminalBackground: true,
    tintColor: ink[1],
    darkModeTintColor: ink[1],
    lightModeTintColor: null,
    tintOpacity: 0.18,
  },

  automation: {
    claudeCodeIntegration: true,
    geminiIntegration: true,
    suppressSubagentNotifications: true,
    socketControlMode: 'cmuxOnly',
  },

  browser: {
    theme: 'dark',
    openTerminalLinksInCmuxBrowser: true,
    interceptTerminalOpenCommandInCmuxBrowser: true,
  },

  diffViewer: {
    defaultLayout: 'split',
  },

  markdown: {
    fontSize: 15,
    // Empty = cmux's proportional system font. The previous config forced
    // JetBrainsMono here, so every README and PR body was read in monospace.
    // Monospace is right for code and wrong for prose.
    fontFamily: '',
    // 980px at 15px proportional is ~120 characters per line — far past the
    // ~70-80 where reading speed drops off.
    maxWidth: 760,
  },
};
emit('cmux/cmux.json', JSON.stringify(cmux, null, 2) + '\n');

// ── wallpaper ──────────────────────────────────────────────────────────────
// Rendered by tools/wallpaper.mjs, not here: this machine has no working SVG
// rasteriser, so the wallpapers are drawn pixel-by-pixel instead.

// ── VS Code ─────────────────────────────────────────────────────────────────
// The whole palette goes into settings.json via colorCustomizations rather
// than being packaged as a theme extension: a dotfiles repo should not need a
// published extension to look right, and this way it is generated from the
// same tokens as everything else.
//
// Verified against VS Code 1.127.0.
const vscode = {
  // ── Focus mode ────────────────────────────────────────────────────────
  // This machine writes code in pi inside cmux. VS Code is a FILE VIEWER, a
  // git/PR surface, and somewhere to open a terminal — so the layout is built
  // around reading, not around authoring.
  //
  // Sidebar on the RIGHT: the eye starts at the left margin of the code, and
  // a tree there pushes every line inward. On the right it is out of the
  // reading path and still one keystroke away.
  'workbench.sideBar.location': 'right',
  // Icons ride on top of that sidebar instead of taking a permanent vertical
  // strip. Not "hidden": with no activity bar the SCM and Explorer views are
  // keyboard-only, which is a worse trade for something used constantly.
  'workbench.activityBar.location': 'top',
  // The secondary sidebar is where Chat lives in 1.127. Closed by default.
  'workbench.secondarySideBar.defaultVisibility': 'hidden',
  'workbench.panel.defaultLocation': 'bottom',

  // Strip the title bar furniture: none of it is used, all of it is noise.
  'window.commandCenter': false,
  'workbench.layoutControl.enabled': false,
  'workbench.navigationControl.enabled': false,
  'workbench.editor.editorActionsLocation': 'hidden',

  // Agent UI off. Agents run in pi, in a terminal — a second agent surface
  // inside the viewer is the thing being avoided, not a feature.
  'chat.agent.enabled': false,

  'workbench.statusBar.visible': true,
  'workbench.editor.showTabs': 'multiple',
  'workbench.editor.tabSizing': 'shrink',
  // Preview tabs: single-clicking through a tree is READING, and it should not
  // leave twenty pinned tabs behind.
  'workbench.editor.enablePreview': true,
  'workbench.editor.limit.enabled': true,
  'workbench.editor.limit.value': 8,
  'workbench.tree.indent': 14,
  'workbench.tree.renderIndentGuides': 'always',
  'workbench.list.smoothScrolling': true,
  'workbench.editor.empty.hint': 'hidden',
  'workbench.startupEditor': 'none',
  'breadcrumbs.enabled': false,
  'editor.minimap.enabled': false,
  'editor.glyphMargin': false,
  'editor.overviewRulerBorder': false,
  'editor.hideCursorInOverviewRuler': true,
  'editor.renderLineHighlight': 'line',
  'editor.occurrencesHighlight': 'off',
  'editor.selectionHighlight': false,
  'editor.lightbulb.enabled': 'off',
  'editor.stickyScroll.enabled': false,
  'window.titleBarStyle': 'custom',
  'window.title': '${rootName}${separator}${activeEditorShort}',

  // Zen mode as a real second gear, not a novelty: keep the line numbers and
  // the status bar, drop everything else, do not go full screen.
  'zenMode.hideLineNumbers': false,
  'zenMode.hideStatusBar': false,
  'zenMode.fullScreen': false,
  'zenMode.centerLayout': false,
  'zenMode.showTabs': 'multiple',

  // ── Type ──────────────────────────────────────────────────────────────
  // Same face and the same 10% extra leading as the terminal, so moving
  // between the editor and a pi session is not a change of typography.
  'editor.fontFamily': '"JetBrainsMono Nerd Font", Menlo, monospace',
  'editor.fontSize': 13,
  'editor.lineHeight': 1.6,
  'editor.fontLigatures': true,
  'terminal.integrated.fontFamily': '"JetBrainsMono Nerd Font"',
  'terminal.integrated.fontSize': 13,
  'terminal.integrated.lineHeight': 1.1,
  'terminal.integrated.cursorStyle': 'block',
  'terminal.integrated.cursorBlinking': false,

  // ── Git ───────────────────────────────────────────────────────────────
  // The built-in SCM view and Timeline cover history without an extension.
  'scm.diffDecorations': 'all',
  // scm.graph.*, not the scm.showHistoryGraph I first reached for — that one
  // does not exist and VS Code would have ignored it without a word.
  'scm.graph.badges': 'filter',
  'scm.graph.pageSize': 50,
  'scm.graph.showIncomingChanges': true,
  'scm.graph.showOutgoingChanges': true,
  'git.decorations.enabled': true,
  'git.autofetch': true,
  'git.confirmSync': false,
  'timeline.pageSize': 50,
  'diffEditor.ignoreTrimWhitespace': false,
  'diffEditor.renderSideBySide': true,

  'explorer.compactFolders': false,
  'explorer.confirmDelete': true,
  'files.trimTrailingWhitespace': true,
  'files.insertFinalNewline': true,

  // ── Iris ──────────────────────────────────────────────────────────────
  'workbench.colorCustomizations': {
    focusBorder: accent.base,
    'selection.background': accent.wash,

    'editor.background': ink[0],
    'editor.foreground': ink[8],
    'editorCursor.foreground': accent.base,
    'editor.selectionBackground': accent.wash,
    'editor.lineHighlightBackground': ink[1],
    'editorLineNumber.foreground': ink[5],
    'editorLineNumber.activeForeground': accent.base,
    'editorIndentGuide.background1': ink[2],
    'editorIndentGuide.activeBackground1': ink[4],
    'editorWhitespace.foreground': ink[2],
    'editorWidget.background': ink[2],
    'editorWidget.border': ink[4],
    'editorHoverWidget.background': ink[2],
    'editorSuggestWidget.background': ink[2],
    'editorSuggestWidget.selectedBackground': ink[3],
    'editorBracketMatch.background': accent.wash,
    'editorBracketMatch.border': accent.deep,

    'sideBar.background': ink[1],
    'sideBar.foreground': ink[7],
    'sideBar.border': ink[2],
    'sideBarSectionHeader.background': ink[1],
    'sideBarSectionHeader.foreground': ink[6],
    'sideBarTitle.foreground': ink[6],

    'activityBar.background': ink[1],
    'activityBar.foreground': ink[8],
    'activityBar.inactiveForeground': ink[5],
    'activityBar.border': ink[2],
    'activityBarBadge.background': accent.base,
    'activityBarBadge.foreground': ink[0],

    'titleBar.activeBackground': ink[1],
    'titleBar.activeForeground': ink[7],
    'titleBar.inactiveBackground': ink[1],
    'titleBar.inactiveForeground': ink[5],
    'titleBar.border': ink[2],

    'statusBar.background': ink[1],
    'statusBar.foreground': ink[7],
    'statusBar.border': ink[2],
    'statusBar.noFolderBackground': ink[1],
    // Debugging is a MODE, not an identity — it gets a state colour, and the
    // accent stays reserved for focus.
    'statusBar.debuggingBackground': state.warning,
    'statusBar.debuggingForeground': ink[0],
    'statusBarItem.remoteBackground': ink[2],
    'statusBarItem.remoteForeground': ink[7],

    'tab.activeBackground': ink[0],
    'tab.activeForeground': ink[9],
    'tab.inactiveBackground': ink[1],
    'tab.inactiveForeground': ink[6],
    'tab.border': ink[2],
    'tab.activeBorderTop': accent.base,
    'tab.unfocusedActiveBorderTop': ink[4],
    'editorGroupHeader.tabsBackground': ink[1],
    'editorGroupHeader.tabsBorder': ink[2],
    'editorGroup.border': ink[2],

    'panel.background': ink[0],
    'panel.border': ink[2],
    'panelTitle.activeForeground': ink[8],
    'panelTitle.inactiveForeground': ink[6],
    'panelTitle.activeBorder': accent.base,

    'list.activeSelectionBackground': accent.wash,
    'list.activeSelectionForeground': ink[9],
    'list.inactiveSelectionBackground': ink[2],
    'list.hoverBackground': ink[2],
    'list.focusOutline': accent.base,

    'input.background': ink[2],
    'input.border': ink[4],
    'inputOption.activeBorder': accent.base,
    'quickInput.background': ink[2],
    'quickInputList.focusBackground': accent.wash,

    'scrollbarSlider.background': `${ink[4]}80`,
    'scrollbarSlider.hoverBackground': `${ink[5]}b0`,
    'scrollbarSlider.activeBackground': `${ink[5]}ff`,

    // Git: status colours, never the accent.
    'gitDecoration.modifiedResourceForeground': state.warning,
    'gitDecoration.addedResourceForeground': state.success,
    'gitDecoration.deletedResourceForeground': state.error,
    'gitDecoration.untrackedResourceForeground': state.special,
    'gitDecoration.ignoredResourceForeground': ink[5],
    'gitDecoration.conflictingResourceForeground': state.error,
    'editorGutter.addedBackground': state.success,
    'editorGutter.modifiedBackground': state.warning,
    'editorGutter.deletedBackground': state.error,
    'diffEditor.insertedTextBackground': `${state.success}22`,
    'diffEditor.removedTextBackground': `${state.error}22`,

    'editorError.foreground': state.error,
    'editorWarning.foreground': state.warning,
    'editorInfo.foreground': state.info,

    // Terminal: the same ANSI palette as Ghostty, so a shell is a shell
    // wherever it is opened.
    'terminal.background': ink[0],
    'terminal.foreground': ink[8],
    'terminalCursor.foreground': accent.base,
    'terminal.ansiBlack': ansi.black,
    'terminal.ansiRed': ansi.red,
    'terminal.ansiGreen': ansi.green,
    'terminal.ansiYellow': ansi.yellow,
    'terminal.ansiBlue': ansi.blue,
    'terminal.ansiMagenta': ansi.magenta,
    'terminal.ansiCyan': ansi.cyan,
    'terminal.ansiWhite': ansi.white,
    'terminal.ansiBrightBlack': ansi.brightBlack,
    'terminal.ansiBrightRed': ansi.brightRed,
    'terminal.ansiBrightGreen': ansi.brightGreen,
    'terminal.ansiBrightYellow': ansi.brightYellow,
    'terminal.ansiBrightBlue': ansi.brightBlue,
    'terminal.ansiBrightMagenta': ansi.brightMagenta,
    'terminal.ansiBrightCyan': ansi.brightCyan,
    'terminal.ansiBrightWhite': ansi.brightWhite,
  },

  // Same syntax hierarchy as the pi theme: what you skim past is dimmest,
  // what carries structure is brightest.
  'editor.tokenColorCustomizations': {
    textMateRules: [
      { scope: ['comment', 'punctuation.definition.comment'], settings: { foreground: ink[6], fontStyle: 'italic' } },
      { scope: ['keyword', 'storage', 'keyword.control'], settings: { foreground: state.special } },
      { scope: ['entity.name.function', 'support.function', 'meta.function-call'], settings: { foreground: accent.base } },
      { scope: ['variable', 'meta.definition.variable.name'], settings: { foreground: ink[8] } },
      { scope: ['string', 'punctuation.definition.string'], settings: { foreground: state.success } },
      { scope: ['constant.numeric', 'constant.language'], settings: { foreground: state.warning } },
      { scope: ['entity.name.type', 'support.type', 'support.class'], settings: { foreground: ansi.cyan } },
      { scope: ['keyword.operator'], settings: { foreground: accent.dim } },
      { scope: ['punctuation'], settings: { foreground: ink[7] } },
      { scope: ['entity.name.tag'], settings: { foreground: state.special } },
      { scope: ['entity.other.attribute-name'], settings: { foreground: state.warning } },
      { scope: ['invalid'], settings: { foreground: state.error } },
    ],
  },
};
emit('vscode/settings.json', JSON.stringify(vscode, null, 2) + '\n');

// ── write / check ───────────────────────────────────────────────────────────
let stale = 0;
for (const { relPath, content } of out) {
  const abs = join(ROOT, relPath);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8') : null;
  if (CHECK) {
    if (current !== content) {
      stale++;
      console.log(`  STALE  ${relPath}`);
    } else {
      console.log(`  ok     ${relPath}`);
    }
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log(`  ${current === content ? 'unchanged' : 'wrote    '}  ${relPath}`);
  }
}

if (CHECK) {
  console.log(stale === 0 ? '\nPASS — generated files match tokens.' : `\nFAIL — ${stale} stale.`);
  process.exit(stale === 0 ? 0 : 1);
}

